CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT,
    start_date TIMESTAMPTZ,
    target_end_date TIMESTAMPTZ,
    actutal_end_date TIMESTAMPTZ,
    create_on TIMESTAMPTZ DEFAULT now() NOT NULL,
    create_by TEXT,
    modified_on TIMESTAMPTZ DEFAULT now() NOT NULL,
    modified_by TEXT,
    visible Boolean
);