CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT,
    start_date TIMESTAMP,
    target_end_date TIMESTAMP,
    actutal_end_date TIMESTAMP,
    create_on TIMESTAMP DEFAULT now()::date NOT NULL,
    create_by TEXT,
    modified_on TIMESTAMP DEFAULT now()::date NOT NULL,
    modified_by TEXT,
    visible Boolean
);