CREATE TABLE tickets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT,
    type TEXT,
    target_end_date TIMESTAMP,
    actutal_end_date TIMESTAMP,
    create_on TIMESTAMP DEFAULT now()::date NOT NULL,
    create_by TEXT,
    modified_on TIMESTAMP DEFAULT now()::date NOT NULL,
    modified_by TEXT,
    visible Boolean,
    assigned_to TEXT,
    project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
    priority TEXT
);