CREATE TABLE tickets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT,
    type TEXT,
    target_end_date TIMESTAMPTZ,
    actutal_end_date TIMESTAMPTZ,
    create_on TIMESTAMPTZ DEFAULT now() NOT NULL,
    create_by TEXT,
    modified_on TIMESTAMPTZ DEFAULT now() NOT NULL,
    modified_by TEXT,
    visible Boolean,
    assigned_to TEXT,
    project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
    priority TEXT
);